CREATE DATABASE IF NOT EXISTS `INASE_DATABASE`;

CREATE TABLE  `INASE_DATABASE`.`SAMPLES` (
    UUID CHAR(36) NOT NULL PRIMARY KEY DEFAULT (UUID()),
    SEAL_NUMBER VARCHAR(50) NOT NULL,
    COMPANY VARCHAR(100) NOT NULL ,
    SPECIES VARCHAR(100) NOT NULL ,
    QUANTITY INT NOT NULL
);

CREATE TABLE `INASE_DATABASE`.`LABORATORY_ANALYSIS` (
    SAMPLE_UUID CHAR(36) NOT NULL,
    GERMINATION_POWER DECIMAL(5,2) NOT NULL,
    PURITY DECIMAL(5,2) NOT NULL,
    INERT_MATERIALS VARCHAR(255),

    CONSTRAINT FK_LAB_ANALYSIS_SAMPLE
    FOREIGN KEY (SAMPLE_UUID)
    REFERENCES `INASE_DATABASE`.`SAMPLES`(UUID)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);





